//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipStajyer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPO()
        {
            this.DEPO_ESLESTIRME = new HashSet<DEPO_ESLESTIRME>();
        }
    
        public int DEPO_ID { get; set; }
        public string DEPO_ADI { get; set; }
        public string STATU { get; set; }
        //sil
        public int OLCU_BIRIMI_ID { get; set; }

        public virtual OLCU_BIRIM OLCU_BIRIM { get; set; }
        //
        public Nullable<int> OLUSTURAN_KULLANICI { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_TARIHI { get; set; }
        public Nullable<int> GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPO_ESLESTIRME> DEPO_ESLESTIRME { get; set; }
    }
}
