//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipStajyer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {

        public int KUL_ID { get; set; }
        public string KUL_USERNAME { get; set; }
        public string KUL_SIFRE { get; set; }
        public string KUL_AD { get; set; }
        public string KUL_SOYAD { get; set; }
        public Nullable<int> KUL_TIP { get; set; }
        public Nullable<bool> STATU { get; set; }
        public Nullable<int> OLUSTURAN_KULLANICI { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_TARIHI { get; set; }
        public Nullable<int> GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
    
        public virtual KULLANICI_TIP KULLANICI_TIP { get; set; }
    }
}
